alias buildsys="sudo nixos-rebuild switch --flake /home/benji/nixcfg/nixos/#benji"
alias onesync="onedrive --synchronize --verbose"
alias geoguessr="electron /home/benji/nixcfg/scripts/webwindow.js"
alias tmr='nix-shell ~/nixcfg/shells/ --run "python ./nixcfg/scripts/python/timer.py"'
alias nxsh="nix-shell ~/nixcfg/shells/"
