alias buildsys="sudo nixos-rebuild switch --flake /home/benji/nixcfg/nixos/#benji"
alias onesync="onedrive --synchronize --verbose"
alias geoguessr="electron /home/benji/nixcfg/scripts/webwindow.js"
alias tmr='nix-shell ~/nixcfg/shells/ --run "python ./nixcfg/scripts/python/timer.py"'
alias nxsh="nix-shell ~/nixcfg/shells/"
alias displ="~/nixcfg/scripts/monitors.sh"

# -------------------------------
# Colors
# -------------------------------
export CLICOLOR=1
export LS_COLORS="di=1;34:ln=1;36:so=1;35:pi=33:ex=1;32:bd=1;33:cd=1;33:su=37;41:sg=30;43:tw=30;42:ow=34;42:*.tar=1;31:*.zip=1;31:*.gz=1;31"
export GREP_COLORS="ms=1;33:mc=1;33:sl=:cx=:fn=1;35:ln=1;32:se=36"

alias ls="ls --color=auto"
alias ll="ls -lh --color=auto"
alias la="ls -lAh --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias diff="diff --color=auto"

parse_git_branch() {
  git branch 2>/dev/null | sed -n '/\* /s///p' | sed 's/\(.*\)/ (\1)/'
}
PS1='\[\e[32m\]\u@\h\[\e[0m\] \[\e[34m\]\w\[\e[0m\]\[\e[33m\]$(parse_git_branch)\[\e[0m\] \[\e[35m\]\$\[\e[0m\] '
