background #000000
foreground #d0d0d0
cursor     #d0d0d0

# normal colors
color0  #000000
color1  #e25b5b
color2  #21db14
color3  #e6d36d
color4  #5da9e2
color5  #d17ad1
color6  #63c6c6
color7  #d0d0d0

# bright colors
color8  #6b6b6b
color9  #ff8787
color10 #5cf24d
color11 #ffe999
color12 #8ec9f5
color13 #e6a6e6
color14 #96e0e0
color15 #ffffff
